/* consts.c generated by valac 0.26.1, the Vala compiler
 * generated from consts.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define CONSTS_name "Leon"
#define CONSTS_version "0.0.1"
#define CONSTS_name_full CONSTS_name " " CONSTS_version
#define CONSTS_debug TRUE

const guint8 CONSTS_version_values[3] = {(guint8) 0, (guint8) 0, (guint8) 1};


