/* main.c generated by valac 0.26.1, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define TYPE_APPLICATION (application_get_type ())
#define APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_APPLICATION, Application))
#define APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_APPLICATION, ApplicationClass))
#define IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_APPLICATION))
#define IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_APPLICATION))
#define APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_APPLICATION, ApplicationClass))

typedef struct _Application Application;
typedef struct _ApplicationClass ApplicationClass;
typedef struct _ApplicationPrivate ApplicationPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Application {
	GObject parent_instance;
	ApplicationPrivate * priv;
};

struct _ApplicationClass {
	GObjectClass parent_class;
};


static gpointer application_parent_class = NULL;

GType application_get_type (void) G_GNUC_CONST;
enum  {
	APPLICATION_DUMMY_PROPERTY
};
Application* application_new (gchar** args, int args_length1);
Application* application_construct (GType object_type, gchar** args, int args_length1);
#define CONSTS_debug TRUE
void application_run (Application* self);
gint _vala_main (gchar** args, int args_length1);


Application* application_construct (GType object_type, gchar** args, int args_length1) {
	Application * self = NULL;
#line 3 "/home/barry/Documents/Projects/leon/src/main.vala"
	self = (Application*) g_object_new (object_type, NULL);
#line 5 "/home/barry/Documents/Projects/leon/src/main.vala"
	if (CONSTS_debug) {
#line 54 "main.c"
		FILE* _tmp0_ = NULL;
#line 6 "/home/barry/Documents/Projects/leon/src/main.vala"
		_tmp0_ = stdout;
#line 6 "/home/barry/Documents/Projects/leon/src/main.vala"
		fprintf (_tmp0_, "Created the application!\n");
#line 60 "main.c"
	}
#line 3 "/home/barry/Documents/Projects/leon/src/main.vala"
	return self;
#line 64 "main.c"
}


Application* application_new (gchar** args, int args_length1) {
#line 3 "/home/barry/Documents/Projects/leon/src/main.vala"
	return application_construct (TYPE_APPLICATION, args, args_length1);
#line 71 "main.c"
}


void application_run (Application* self) {
#line 9 "/home/barry/Documents/Projects/leon/src/main.vala"
	g_return_if_fail (self != NULL);
#line 78 "main.c"
}


static void application_class_init (ApplicationClass * klass) {
#line 1 "/home/barry/Documents/Projects/leon/src/main.vala"
	application_parent_class = g_type_class_peek_parent (klass);
#line 85 "main.c"
}


static void application_instance_init (Application * self) {
}


GType application_get_type (void) {
	static volatile gsize application_type_id__volatile = 0;
	if (g_once_init_enter (&application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Application), 0, (GInstanceInitFunc) application_instance_init, NULL };
		GType application_type_id;
		application_type_id = g_type_register_static (G_TYPE_OBJECT, "Application", &g_define_type_info, 0);
		g_once_init_leave (&application_type_id__volatile, application_type_id);
	}
	return application_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	Application* app = NULL;
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	Application* _tmp1_ = NULL;
#line 17 "/home/barry/Documents/Projects/leon/src/main.vala"
	_tmp0_ = args;
#line 17 "/home/barry/Documents/Projects/leon/src/main.vala"
	_tmp0__length1 = args_length1;
#line 17 "/home/barry/Documents/Projects/leon/src/main.vala"
	_tmp1_ = application_new (_tmp0_, _tmp0__length1);
#line 17 "/home/barry/Documents/Projects/leon/src/main.vala"
	app = _tmp1_;
#line 18 "/home/barry/Documents/Projects/leon/src/main.vala"
	application_run (app);
#line 20 "/home/barry/Documents/Projects/leon/src/main.vala"
	result = 0;
#line 20 "/home/barry/Documents/Projects/leon/src/main.vala"
	_g_object_unref0 (app);
#line 20 "/home/barry/Documents/Projects/leon/src/main.vala"
	return result;
#line 127 "main.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 15 "/home/barry/Documents/Projects/leon/src/main.vala"
	return _vala_main (argv, argc);
#line 137 "main.c"
}



